" .vimrc
" A Vim configuration
" JeanCarlos
" https:/github.com/jeancarlos-ing/dotfiles

set nocompatible
setglobal encoding=utf-8
setglobal fileencoding=utf-8
scriptencoding utf-8
set sessionoptions=blank,curdir,folds,help,tabpages,unix,slash
set viewoptions=folds,options,cursor,curdir,unix,slash
set termguicolors
filetype plugin indent on
syntax enable
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set textwidth=0
set formatoptions+=w
set formatoptions+=c
set formatoptions-=o
set formatoptions-=l
set autoindent
set smartindent
set cindent
set smarttab
set backspace=indent,eol,start
set conceallevel=2
set showmode
set suffixes=.bak,~,.swap,.swo
set showmatch
set tabpagemax=30
set history=400
set undolevels=2000
set undoreload=10000
set number
set relativenumber
set errorbells
set visualbell
set belloff=all
set autoread
set laststatus=2
set showtabline=2
set printoptions=paper:letter
set linebreak
set showbreak
set cpoptions+=n
set scrolloff=0
set sidescroll=5
set wrapscan
set wrap
set ignorecase
set incsearch
set smartcase
set startofline
set nrformats-=octal
set hlsearch
set writeany
set showcmd
set ruler
set helpheight=25
set winwidth=10
set splitbelow
set mousemodel=popup
set mouse=nivc
set ttyfast
set lazyredraw
set cursorline
set colorcolumn=80
